# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name: "Ash", username: "Ash")
User.create(name: "Brock", username: "Brock")
User.create(name: "Misty", username: "Misty")
Pokemon.create(name: "Pikachu", pokemon_type: "Electric")
Pokemon.create(name: "Butterfree", pokemon_type: "Bug")
Pokemon.create(name: "Pidgeot", pokemon_type: "Flying")
Pokemon.create(name: "Charizard", pokemon_type: "Fire")
Pokemon.create(name: "Bulbasaur", pokemon_type: "Grass")
Pokemon.create(name: "Squirtle", pokemon_type: "Water")
Pokeball.create(pokemon_id: 1, user_id: 1)
Pokeball.create(pokemon_id: 2, user_id: 1)
Pokeball.create(pokemon_id: 3, user_id: 1)
Pokeball.create(pokemon_id: 4, user_id: 1)
Pokeball.create(pokemon_id: 5, user_id: 1)
Pokeball.create(pokemon_id: 6, user_id: 1)
Pokemon.create(name: "Geodude", pokemon_type: "Rock")
Pokemon.create(name: "Onix", pokemon_type: "Rock")
Pokeball.create(pokemon_id: 7, user_id: 2)
Pokeball.create(pokemon_id: 8, user_id: 2)
Pokemon.create(name: "Staryu", pokemon_type: "Water")
Pokemon.create(name: "Goldeen", pokemon_type: "Water")
Pokeball.create(pokemon_id: 9, user_id: 3)
Pokeball.create(pokemon_id: 10, user_id: 3)
Move.create(name: "Thunderbolt", move_type: "Electric", pokemon_id: 1)
Move.create(name: "Thundershock", move_type: "Electric", pokemon_id: 1)
Move.create(name: "Thunderwave", move_type: "Electric", pokemon_id: 1)
Move.create(name: "Sleep Powder", move_type: "Grass", pokemon_id: 2)
Move.create(name: "Poison Powder", move_type: "Poison", pokemon_id: 2)
Move.create(name: "Tackle", move_type: "Normal", pokemon_id: 2)
Move.create(name: "Gust", move_type: "Flying", pokemon_id: 3)
Move.create(name: "Wing Attack", move_type: "Flying", pokemon_id: 3)
Move.create(name: "Quick Attack", move_type: "Normal", pokemon_id: 3)
Move.create(name: "Fire Spin", move_type: "Fire", pokemon_id: 4)
Move.create(name: "Flamethrower", move_type: "Fire", pokemon_id: 4)
Move.create(name: "Slash", move_type: "Normal", pokemon_id: 4)
Move.create(name: "Solarbeam", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Leech Seed", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Razor Leaf", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Vine Whip", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Bubble", move_type: "Water", pokemon_id: 6)
Move.create(name: "Water Gun", move_type: "Water", pokemon_id: 6)
Move.create(name: "Bite", move_type: "Normal", pokemon_id: 6)
Move.create(name: "Hydro Pump", move_type: "Water", pokemon_id: 6)
Move.create(name: "Rock Throw", move_type: "Rock", pokemon_id: 7)
Move.create(name: "Harden", move_type: "Normal", pokemon_id: 7)
Move.create(name: "Selfdestruct", move_type: "Normal", pokemon_id: 7)
Move.create(name: "Bind", move_type: "Normal", pokemon_id: 8)
Move.create(name: "Rage", move_type: "Normal", pokemon_id: 8)
Move.create(name: "Screech", move_type: "Normal", pokemon_id: 8)
Move.create(name: "Swift", move_type: "Normal", pokemon_id: 9)
Move.create(name: "Tackle", move_type: "Normal", pokemon_id: 9)
Move.create(name: "Recover", move_type: "Normal", pokemon_id: 9)
Move.create(name: "Peck", move_type: "Flying", pokemon_id: 10)
Move.create(name: "Horn Attack", move_type: "Normal", pokemon_id: 10)
Move.create(name: "Bubblebeam", move_type: "Water", pokemon_id: 10)
