# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name: "Ash", username: "Ash", img_url: "https://upload.wikimedia.org/wikipedia/en/thumb/0/09/AshXYanime.png/220px-AshXYanime.png")
User.create(name: "Brock", username: "Brock", img_url: "https://static.minichan.org/img/142543583484441.png")
User.create(name: "Misty", username: "Misty", img_url: "https://mtbifiction.files.wordpress.com/2015/09/misty-misty-22975692-640-480.png?w=665")
Pokemon.create(name: "Pikachu", pokemon_type: "Electric", imgurl: "https://cdn.bulbagarden.net/upload/thumb/0/0d/025Pikachu.png/500px-025Pikachu.png")
Pokemon.create(name: "Butterfree", pokemon_type: "Bug", imgurl: "https://cdn.bulbagarden.net/upload/thumb/d/d1/012Butterfree.png/250px-012Butterfree.png")
Pokemon.create(name: "Pidgeot", pokemon_type: "Flying", imgurl: "https://cdn.bulbagarden.net/upload/thumb/5/57/018Pidgeot.png/250px-018Pidgeot.png")
Pokemon.create(name: "Charizard", pokemon_type: "Fire", imgurl: "https://cdn.bulbagarden.net/upload/thumb/7/7e/006Charizard.png/250px-006Charizard.png")
Pokemon.create(name: "Bulbasaur", pokemon_type: "Grass", imgurl: "https://cdn.bulbagarden.net/upload/thumb/2/21/001Bulbasaur.png/250px-001Bulbasaur.png")
Pokemon.create(name: "Squirtle", pokemon_type: "Water", imgurl: "https://cdn.bulbagarden.net/upload/thumb/3/39/007Squirtle.png/250px-007Squirtle.png")
Pokeball.create(pokemon_id: 1, user_id: 1)
Pokeball.create(pokemon_id: 2, user_id: 1)
Pokeball.create(pokemon_id: 3, user_id: 1)
Pokeball.create(pokemon_id: 4, user_id: 1)
Pokeball.create(pokemon_id: 5, user_id: 1)
Pokeball.create(pokemon_id: 6, user_id: 1)
Pokemon.create(name: "Geodude", pokemon_type: "Rock", imgurl: "https://cdn.bulbagarden.net/upload/thumb/9/98/074Geodude.png/250px-074Geodude.png")
Pokemon.create(name: "Onix", pokemon_type: "Rock", imgurl: "https://cdn.bulbagarden.net/upload/thumb/9/9a/095Onix.png/500px-095Onix.png")
Pokeball.create(pokemon_id: 7, user_id: 2)
Pokeball.create(pokemon_id: 8, user_id: 2)
Pokemon.create(name: "Staryu", pokemon_type: "Water", imgurl: "https://cdn.bulbagarden.net/upload/thumb/4/4f/120Staryu.png/250px-120Staryu.png")
Pokemon.create(name: "Goldeen", pokemon_type: "Water", imgurl: "https://cdn.bulbagarden.net/upload/7/7b/118Goldeen.png")
Pokeball.create(pokemon_id: 9, user_id: 3)
Pokeball.create(pokemon_id: 10, user_id: 3)
Move.create(name: "Thunderbolt", move_type: "Electric", pokemon_id: 1)
Move.create(name: "Thundershock", move_type: "Electric", pokemon_id: 1)
Move.create(name: "Thunderwave", move_type: "Electric", pokemon_id: 1)
Move.create(name: "Sleep Powder", move_type: "Grass", pokemon_id: 2)
Move.create(name: "Poison Powder", move_type: "Poison", pokemon_id: 2)
Move.create(name: "Tackle", move_type: "Normal", pokemon_id: 2)
Move.create(name: "Gust", move_type: "Flying", pokemon_id: 3)
Move.create(name: "Wing Attack", move_type: "Flying", pokemon_id: 3)
Move.create(name: "Quick Attack", move_type: "Normal", pokemon_id: 3)
Move.create(name: "Fire Spin", move_type: "Fire", pokemon_id: 4)
Move.create(name: "Flamethrower", move_type: "Fire", pokemon_id: 4)
Move.create(name: "Slash", move_type: "Normal", pokemon_id: 4)
Move.create(name: "Solarbeam", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Leech Seed", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Razor Leaf", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Vine Whip", move_type: "Grass", pokemon_id: 5)
Move.create(name: "Bubble", move_type: "Water", pokemon_id: 6)
Move.create(name: "Water Gun", move_type: "Water", pokemon_id: 6)
Move.create(name: "Bite", move_type: "Normal", pokemon_id: 6)
Move.create(name: "Hydro Pump", move_type: "Water", pokemon_id: 6)
Move.create(name: "Rock Throw", move_type: "Rock", pokemon_id: 7)
Move.create(name: "Harden", move_type: "Normal", pokemon_id: 7)
Move.create(name: "Selfdestruct", move_type: "Normal", pokemon_id: 7)
Move.create(name: "Rock Throw", move_type: "Rock", pokemon_id: 8)
Move.create(name: "Bind", move_type: "Normal", pokemon_id: 8)
Move.create(name: "Rage", move_type: "Normal", pokemon_id: 8)
Move.create(name: "Screech", move_type: "Normal", pokemon_id: 8)
Move.create(name: "Swift", move_type: "Normal", pokemon_id: 9)
Move.create(name: "Tackle", move_type: "Normal", pokemon_id: 9)
Move.create(name: "Recover", move_type: "Normal", pokemon_id: 9)
Move.create(name: "Peck", move_type: "Flying", pokemon_id: 10)
Move.create(name: "Horn Attack", move_type: "Normal", pokemon_id: 10)
Move.create(name: "Bubblebeam", move_type: "Water", pokemon_id: 10)
Pokemon.create(name: "Charmander", pokemon_type: "Fire", imgurl: "https://cdn.bulbagarden.net/upload/thumb/7/73/004Charmander.png/250px-004Charmander.png")
Pokemon.create(name: "Charmeleon", pokemon_type: "Fire", imgurl: "https://cdn.bulbagarden.net/upload/thumb/4/4a/005Charmeleon.png/250px-005Charmeleon.png")
Pokemon.create(name: "Ivysaur", pokemon_type: "Grass", imgurl: "https://cdn.bulbagarden.net/upload/thumb/2/21/001Bulbasaur.png/250px-001Bulbasaur.png")
Pokemon.create(name: "Venusaur", pokemon_type: "Grass", imgurl: "https://cdn.bulbagarden.net/upload/thumb/7/73/002Ivysaur.png/250px-002Ivysaur.png")
Pokemon.create(name: "Wartortle", pokemon_type: "Water", imgurl: "https://cdn.bulbagarden.net/upload/thumb/0/0c/008Wartortle.png/250px-008Wartortle.png")
Pokemon.create(name: "Blastoise", pokemon_type: "Water", imgurl: "https://cdn.bulbagarden.net/upload/thumb/0/02/009Blastoise.png/1200px-009Blastoise.png")
Move.create(name: "Ember", move_type: "Fire", pokemon_id: 11)
Move.create(name: "Scratch", move_type: "Normal", pokemon_id: 11)
Move.create(name: "Growl", move_type: "Normal", pokemon_id: 11)
Move.create(name: "Leer", move_type: "Normal", pokemon_id: 11)
Move.create(name: "Ember", move_type: "Fire", pokemon_id: 12)
Move.create(name: "Flamethrower", move_type: "Fire", pokemon_id: 12)
Move.create(name: "Rage", move_type: "Normal", pokemon_id: 12)
Move.create(name: "Slash", move_type: "Normal", pokemon_id: 12)
Move.create(name: "Tackle", move_type: "Normal", pokemon_id: 13)
Move.create(name: "Solarbeam", move_type: "Grass", pokemon_id: 13)
Move.create(name: "Vine Whip", move_type: "Grass", pokemon_id: 13)
Move.create(name: "Razor Leaf", move_type: "Grass", pokemon_id: 13)
Move.create(name: "Poison Powder", move_type: "Poison", pokemon_id: 14)
Move.create(name: "Solarbeam", move_type: "Grass", pokemon_id: 14)
Move.create(name: "Vine Whip", move_type: "Grass", pokemon_id: 14)
Move.create(name: "Razor Leaf", move_type: "Grass", pokemon_id: 14)
Move.create(name: "Bubblebeam", move_type: "Water", pokemon_id: 15)
Move.create(name: "Hydro Pump", move_type: "Water", pokemon_id: 15)
Move.create(name: "Water Gun", move_type: "Water", pokemon_id: 15)
Move.create(name: "Skull Bash", move_type: "Normal", pokemon_id: 15)
Move.create(name: "Bubblebeam", move_type: "Water", pokemon_id: 16)
Move.create(name: "Ice Beam", move_type: "Ice", pokemon_id: 16)
Move.create(name: "Hydro Pump", move_type: "Water", pokemon_id: 16)
Move.create(name: "Surf", move_type: "Water", pokemon_id: 16)
